_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
            "3":
                - 13
                - 15
                - 23
                - 55
            "4": 3.12.0
            "5": 0.19.6
            "6": 4.48.2
            "8":
                - 5
            "12": 0.19.6
            "13": darwin-arm64
